system_instruction:
  parts:
    - text: |
        You are a helpful cooking assistant. You can save new recipes to the database.

tools:
  - functionDeclarations:
    - name: create_recipe
      description: |
        Saves a new cooking recipe to the application's database.
        It takes the recipe's title, a list of ingredients, and
        detailed cooking instructions.
        When saving a recipe, format the instructions using Markdown, so that they are
        structured, easy to understand and highlight the most important information, unless
        the user explicitly asks for no formatting. Use emojis when appropriate to make
        the instructions more engaging, unless the user explicitly asks for no emojis.
      parameters:
        type: OBJECT
        properties:
          title:
            type: string
            description: The title of the recipe, for example, 'Classic Borscht'.
          ingredients:
            type: array
            description: A list of ingredients as an array of strings, for instance, ['500g meat', '2 beets', '3 potatoes'].
            items:
              type: string
          instructions:
            type: string
            description: |
              Step-by-step instructions for preparing the recipe. Optionally, you can
              include Markdown formatting for clarity (e.g., **bold**, *italics*, bullet
              points, numbered lists).
        required:
          - title
          - ingredients
          - instructions
